
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  namespace: {{ .Release.Namespace | default "cloud-ninjas" }}
type: Opaque
data:
  DB_HOST: {{ .Values.backend.secret.dbHost | b64enc }}
  DB_USER: {{ .Values.backend.secret.dbUser | b64enc }}
  DB_PASS: {{ .Values.backend.secret.dbPass | b64enc }}
  DB_NAME: {{ .Values.backend.secret.dbName | b64enc }}
  REDIS_HOST: {{ .Values.backend.secret.redisHost | b64enc }}