# backend-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: cloud-ninjas
type: Opaque
data:
  # استبدل القيم أدناه بقيم قوية قبل التشغيل في production
  DB_HOST: bXlzcWw=              # "mysql" ← اسم service MySQL في k8s
  DB_USER: Y2xvdWRuaW5qYXM= # "cloudninjas" ← must match MySQL user          
  DB_PASS: cm9vdDEyMw==          # "root123"
  DB_NAME: Y2xvdWRuaW5qYXM=      # "cloudninjas"
  REDIS_HOST: cmVkaXM=           # "redis" ← اسم service Redis في k8s