apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cloud-ninjas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: selconyt/backend:v1.1  # تأكد من وجود cryptography
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_PASS
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_NAME
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: REDIS_HOST
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: cloud-ninjas
spec:
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP  # or NodePort if you need external access