apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: cloud-ninjas
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.44
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: { secretKeyRef: { name: db-secret, key: DB_PASS } }
        - name: MYSQL_USER          # ← ADD THIS
          valueFrom: { secretKeyRef: { name: db-secret, key: DB_USER } }
        - name: MYSQL_PASSWORD      # ← ADD THIS
          valueFrom: { secretKeyRef: { name: db-secret, key: DB_PASS } }
        - name: MYSQL_DATABASE
          valueFrom: { secretKeyRef: { name: db-secret, key: DB_NAME } }
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "mysqladmin shutdown -uroot -p${MYSQL_ROOT_PASSWORD}"]
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: cloud-ninjas
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: cloud-ninjas
spec:
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql