# db-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: cloud-ninjas
type: Opaque
data:
  # Use base64-encoded values (you can generate them with `echo -n 'value' | base64`)
data:
  DB_USER: Y2xvdWRuaW5qYXM= # "cloudninjas"
  DB_PASS: cm9vdDEyMw==     # "root123" (or better: strong password)
  DB_NAME: Y2xvdWRuaW5qYXM= # "cloudninjas"
  # DB_HOST not needed by MySQL StatefulSet