apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: cloud-ninjas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: omaradel2001/frontend:v1.0
        name: frontend
        env:
        - name: BACKEND_URL
          value: "http://api.cloud-ninjas.example.com"
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: cloud-ninjas
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501

