# rolebinding-app.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-pod-reader
  namespace: cloud-ninjas
subjects:
- kind: ServiceAccount
  name: cloud-ninjas-sa      # ← Your app's service account
  namespace: cloud-ninjas
roleRef:
  kind: Role
  name: cloud-ninjas-pod-reader
  apiGroup: rbac.authorization.k8s.io